version: '3.9'

services:
  jsapp:
    container_name: jsapp
    image: aminenait/jsapp
    build:
      context: js
    ports:
      - '3000:3000'
    environment:
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - EXTERNALPORT=3000
    depends_on:
      - db

  pythonapp:
    container_name: pythonapp
    image: aminenait/pythonapp
    build:
      context: python
    ports:
      - '80:80'
    environment:
      - DB_URI=postgresql://postgres:postgres@5701/postgres
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - '5701:5701'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
